### ISSUE TITLE
Text copy

### ISSUE THREAD

**Issue by sman-cn** [zmeid/pretty-diff-text#1]
Great widget! Thank you! 
Would you consider adding a parameter for text copying?
Or,Is there any way to select and copy text?
Thanks!

**Comment by zmeid** [comment]
Thank you!

I don't think there is much value in making the text selectable. If you copy this text:

![Snapshot](https://i.imgur.com/fGNXMYSl.png)

you will get "Your oldnew text" without any styling or color that would demonstrate the text difference.

**Comment by sman-cn** [comment]
Thanks!
In my case, compare the original name with the new name, use your plugin to display the modification of the old name, and sometimes want to copy the deleted text from the old name, and then modify the new name. Do you have a way to make it selectable to copy? I'm a beginner ,Thank you so much! ☺️
