### ISSUE TITLE
2 line compare

### ISSUE THREAD

**Issue by PhuCG** [zmeid/pretty-diff-text#4]
Can you please do it on 2 lines so we can compare, thank you very much

**Comment by zmeid** [comment]
Hi @PhuCG . What do you exactly mean with 2 lines?

**Comment by PhuCG** [comment]
Hi, thanks for your response!! My ideal is to make code to compare words
your code just compares characters.
Example like the below image
![image](https://github.com/zmeid/pretty-diff-text/assets/103182838/e1263f47-e197-4e5b-a435-7a1c749ffe5b)
note: I forked your repo and did that; do you want to see it?

**Comment by zmeid** [comment]
So, as far as I understand, you want to be able to see the original and changed text and compare them. If so, unfortunately, this is out of scope for now.
